
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: events_app_development

test:
  <<: *default
  database: events_app_test

production:
  <<: *default
  database: events_app_production
  username: events_app
  password: <%= ENV['EVENTS_APP_DATABASE_PASSWORD'] %>
